{% set name = "travo" %}
{% set version = "1.1.2" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/travo-{{ version }}.tar.gz
  sha256: 38de3c9fe8c739e109c068143bdcf039d0d78706a421dc382965cc12d46945e0

build:
  noarch: python
  number: 0
  entry_points:
    - travo = travo.console_scripts:travo
    - travo-echo-travo-token = travo.console_scripts:travo_echo_travo_token

outputs:
  - name: travo
    build:
      noarch: python
    script: build_travo.sh
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >={{ python_min }}
        - colorlog
        - dataclasses
        - deprecation
        - typing_utils
        - requests
        - tqdm
        - anybadge
        - i18nice
        - pyyaml
    test:
      imports:
        - travo
      commands:
        - pip check
        - travo --help
      requires:
        - pip

  - name: travo-jupyter
    build:
      noarch: python
    script: build_travo-jupyter.sh
    requirements:
      host:
        - python {{ python_min }}
        - {{ pin_subpackage('travo', exact=True) }}
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('travo', exact=True) }}
        - colorlog
        - dataclasses
        - deprecation
        - typing_utils
        - requests
        - tqdm
        - anybadge
        - i18nice
        - pyyaml
        - nbgrader
        - numpy
        - pandas
        - ipylab
        - ipywidgets
        - ipydatagrid
        - jupytext
    test:
      imports:
        - travo
      commands:
        - pip check
        - travo --help
      requires:
        - pip
        - python {{ python_min }}

about:
  summary: Management tools for gitlab-based assignment workflows
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://gitlab.com/travo-cr/travo
  description: |
    Travo ([tʁa’vo]) is a lightweight open source Python toolkit that turns your favorite
    forge into a flexible management solution for computer assignments. It takes its name
    from the practice sessions linked to a course, called in French "Travaux Pratiques".
  doc_url: https://travo-cr.gitlab.io/travo/
  dev_url: https://travo-cr.gitlab.io/travo/contributing.html

extra:
  feedstock-name: travo
  recipe-maintainers:
    - cmarmo
